### ISSUE TITLE
Copyright materials

### ISSUE THREAD

**Issue by jcuenod** [sil-ai/gloo-hackathon-2023#1]
Hey all,
Just a note that a number of the Bible versions here are copyrighted. I suspect publishers would not appreciate seeing their content on Github like this...

**Comment by woodwardmw** [comment]
@jcuenod Thanks for pointing that out. I think this started as a private repo for experimenting, and then needed to be made public for the hackathon, but I should have removed the copyrighted texts at that point. I'll do that now.
